import type { PhraseRow } from "@/i18n/phraseRows";

export const AUTH_ROWS: PhraseRow[] = [
  ["登入議場", "Enter the chamber", "Entrer dans la salle", "Entrar a la sala", "Войти в зал", "ادخل القاعة"],
  ["使用 Google 帳號登入。登入後，你的進度會依帳號分開保存在這部瀏覽器。", "Sign in with Google. After that, your progress is kept separately for this account in this browser.", "Connecte-toi avec Google. Ensuite, tes progrès restent séparés pour ce compte dans ce navigateur.", "Inicia sesión con Google. Después, tu progreso se guarda por separado para esta cuenta en este navegador.", "Войдите через Google. После этого прогресс этого аккаунта хранится отдельно в этом браузере.", "سجّل الدخول بحساب Google. بعد ذلك يُحفظ تقدّمك لهذا الحساب منفصلًا في هذا المتصفح."],
  ["使用 Google 登入", "Sign in with Google", "Se connecter avec Google", "Iniciar sesión con Google", "Войти через Google", "تسجيل الدخول عبر Google"],
  ["需要在 Firebase 主控台開啟 Google 登入，並把本機與正式網址加入授權網域。", "Enable Google sign-in in the Firebase console, and add localhost plus your live site to authorized domains.", "Active la connexion Google dans la console Firebase, et ajoute localhost ainsi que ton site en ligne aux domaines autorisés.", "Activa el inicio de sesión con Google en la consola de Firebase y añade localhost y tu sitio en vivo a los dominios autorizados.", "Включите вход через Google в консоли Firebase и добавьте localhost и живой сайт в разрешённые домены.", "فعّل تسجيل الدخول عبر Google في وحدة تحكم Firebase، وأضف localhost وموقعك الحي إلى النطاقات المصرّح بها."],
  ["瀏覽器擋下了登入視窗。請允許彈出視窗，或再試一次。", "The browser blocked the sign-in window. Allow pop-ups, or try again.", "Le navigateur a bloqué la fenêtre de connexion. Autorise les pop-ups, ou réessaie.", "El navegador bloqueó la ventana de inicio de sesión. Permite ventanas emergentes o inténtalo de nuevo.", "Браузер заблокировал окно входа. Разрешите всплывающие окна или попробуйте снова.", "حظر المتصفح نافذة تسجيل الدخول. اسمح بالنوافذ المنبثقة أو أعد المحاولة."],
  ["登入視窗已關閉。若要進入議場，請再按一次 Google 登入。", "The sign-in window was closed. To enter the chamber, press Google sign-in again.", "La fenêtre de connexion a été fermée. Pour entrer, appuie encore sur la connexion Google.", "Se cerró la ventana de inicio de sesión. Para entrar, vuelve a pulsar el inicio con Google.", "Окно входа закрыто. Чтобы войти в зал, снова нажмите вход через Google.", "أُغلقت نافذة تسجيل الدخول. للدخول إلى القاعة، اضغط تسجيل الدخول عبر Google مرة أخرى."],
  ["網路連線失敗。請檢查網路後再試。", "The network request failed. Check your connection and try again.", "La requête réseau a échoué. Vérifie ta connexion et réessaie.", "Falló la solicitud de red. Revisa tu conexión e inténtalo de nuevo.", "Сетевой запрос не удался. Проверьте соединение и попробуйте снова.", "فشل طلب الشبكة. تحقق من اتصالك ثم أعد المحاولة."],
  ["已取消登入。", "Sign-in was cancelled.", "La connexion a été annulée.", "Se canceló el inicio de sesión.", "Вход отменён.", "أُلغي تسجيل الدخول."],
  ["這個網址尚未加入 Firebase 授權網域。請在 Firebase 主控台加入目前網址。", "This address is not yet an authorized Firebase domain. Add the current site in the Firebase console.", "Cette adresse n'est pas encore un domaine Firebase autorisé. Ajoute le site actuel dans la console Firebase.", "Esta dirección aún no es un dominio autorizado de Firebase. Añade el sitio actual en la consola de Firebase.", "Этот адрес ещё не входит в разрешённые домены Firebase. Добавьте текущий сайт в консоли Firebase.", "هذا العنوان ليس بعد نطاقًا مصرّحًا في Firebase. أضف الموقع الحالي في وحدة تحكم Firebase."],
  ["Google 登入暫時失敗。請稍後再試。", "Google sign-in failed for now. Try again later.", "La connexion Google a échoué pour l'instant. Réessaie plus tard.", "El inicio con Google falló por ahora. Inténtalo más tarde.", "Вход через Google пока не удался. Попробуйте позже.", "فشل تسجيل الدخول عبر Google الآن. حاول لاحقًا."],
  ["處理中…", "Working…", "Traitement…", "Procesando…", "Обработка…", "جارٍ المعالجة…"],
  ["代表", "Delegate", "Délégué", "Delegado", "Делегат", "المندوب"],
  ["登出", "Log out", "Se déconnecter", "Cerrar sesión", "Выйти", "تسجيل الخروج"],
];
