import type { EvidenceSentence } from "@/types/game";

/** Extra dossier bullets with public newspaper / government / UN report links. */
export const REFERENCE_SENTENCES: EvidenceSentence[] = [
  {
    id: "ref-ke-moe",
    speakerId: "kenya",
    origin: "肯尼亞教育部門公開材料",
    sourceLabel: "肯尼亞教育部門公開材料",
    href: "https://www.education.go.ke/",
    tags: ["warning", "community", "grant"],
    text: "肯尼亞教育部公開材料把農村教師部署、女童中學完成率，以及能觸達社區學校的學習支持列為優先事項。",
  },
  {
    id: "ref-ke-news",
    speakerId: "kenya",
    origin: "路透社教育報導摘要",
    sourceLabel: "路透社教育報導摘要",
    href: "https://www.reuters.com/world/africa/",
    tags: ["debt", "grant", "community"],
    text: "國際新聞報導指出，東非多國在償債壓力上升時，公共教育預算更容易被擠壓，農村學校與女童留校首當其衝。",
  },
  {
    id: "ref-bd-moedu",
    speakerId: "bangladesh",
    origin: "孟加拉教育部公開頁",
    sourceLabel: "孟加拉教育部公開頁",
    href: "https://moedu.gov.bd/",
    tags: ["community", "warning", "access"],
    text: "孟加拉教育部公開資訊強調基礎教育覆蓋、女童入學與地方層級的學習支持網絡。",
  },
  {
    id: "ref-bd-unicef",
    speakerId: "bangladesh",
    origin: "聯合國兒童基金會孟加拉教育頁",
    sourceLabel: "聯合國兒童基金會孟加拉教育頁",
    href: "https://www.unicef.org/bangladesh/en/education",
    tags: ["warning", "community", "grant"],
    text: "UNICEF 孟加拉教育頁指出，社區學習支持與女童留校措施，有助降低學期中的輟學風險。",
  },
  {
    id: "ref-br-mec",
    speakerId: "brazil",
    origin: "巴西教育部公開頁",
    sourceLabel: "巴西教育部公開頁",
    href: "https://www.gov.br/mec/pt-br",
    tags: ["nature", "governance", "equity"],
    text: "巴西教育部公開材料把全納教育、多樣性與學習者支持寫進國家教育政策討論。",
  },
  {
    id: "ref-br-unesco",
    speakerId: "brazil",
    origin: "聯合國教科文組織全納教育專頁",
    sourceLabel: "聯合國教科文組織全納教育專頁",
    href: "https://www.unesco.org/en/inclusion-education",
    tags: ["nature", "equity"],
    text: "UNESCO 全納教育專頁強調：障礙學習者、語言少數群體與邊緣社區必須被算進優質教育，而不只是校舍統計。",
  },
  {
    id: "ref-de-bmz",
    speakerId: "germany",
    origin: "德國聯邦經濟合作與發展部",
    sourceLabel: "德國聯邦經濟合作與發展部",
    href: "https://www.bmz.de/en",
    tags: ["accountability", "report", "public-finance"],
    text: "德國發展合作官方頁把可預測援助、透明與成果核對，列為教育與發展合作的重要條件。",
  },
  {
    id: "ref-de-gem",
    speakerId: "germany",
    origin: "聯合國教科文組織全球教育監測報告",
    sourceLabel: "聯合國教科文組織全球教育監測報告",
    href: "https://www.unesco.org/gem-report/en",
    tags: ["accountability", "report", "scale"],
    text: "UNESCO 全球教育監測報告持續追蹤各國教育資金、公平與學習成果，並提醒公開報告要能被公眾核對。",
  },
  {
    id: "ref-cn-moe",
    speakerId: "china",
    origin: "中國教育部英文公開頁",
    sourceLabel: "中國教育部英文公開頁",
    href: "https://en.moe.gov.cn/",
    tags: ["public-finance", "cbdr"],
    text: "中國教育部公開材料強調擴大教育機會與國際教育交流，同時把教師培訓寫進對外合作敘事。",
  },
  {
    id: "ref-cn-un",
    speakerId: "china",
    origin: "聯合國永續發展目標 4 專頁",
    sourceLabel: "聯合國永續發展目標 4 專頁",
    href: "https://sdgs.un.org/goals/goal4",
    tags: ["cbdr", "public-finance", "scale"],
    text: "聯合國 SDG 4 專頁提醒：優質教育需要可預測的公共資源，發達國家的援助承諾與國內動員同樣重要。",
  },
  {
    id: "ref-us-usaid",
    speakerId: "usa",
    origin: "美國國際開發署教育專頁",
    sourceLabel: "美國國際開發署教育專頁",
    href: "https://www.usaid.gov/education",
    tags: ["private", "voluntary", "access"],
    text: "美國對外援助教育專頁強調基礎學習、技能與夥伴合作，並常把民間與科技夥伴寫進方案設計。",
  },
  {
    id: "ref-us-news",
    speakerId: "usa",
    origin: "BBC 全球教育報導摘要",
    sourceLabel: "BBC 全球教育報導摘要",
    href: "https://www.bbc.com/news/education",
    tags: ["private", "voluntary", "grant"],
    text: "國際媒體教育專題常指出：私人與科技資金較容易流向可收費技能產品，農村基礎教育仍高度依賴公共資源。",
  },
];
